version: "3.8"

services:
    user_service:
        build: ./user_service
        container_name: user_service
        ports:
            - "8080:8000"
        depends_on:
            - user_db
        environment:
            DATABASE_URL: postgresql://postgres:user_db_password@user_db:5432/user_db
        env_file:
            - ./user_service/.env

    product_service:
        build: ./product_service
        container_name: product_service
        ports:
            - "8002:8000"
        depends_on:
            - product_db
        environment:
            DATABASE_URL: postgresql://postgres:product_db_password@product_db:5443/product_db
        env_file:
            - ./product_service/.env

    gateway:
        build: ./gateway
        container_name: gateway
        ports:
            - "8000:8000"
        depends_on:
            - user_service
            - product_service
        environment:
            USER_SERVICE_URL: http://user_service:8000
            PRODUCT_SERVICE_URL: http://product_service:8000

    #    frontend:
    #        build: ./frontend
    #        container_name: frontend
    #        ports:
    #            - "3000:5173"
    #        depends_on:
    #            - user_service
    #            - product_service

    user_db:
        image: postgres:15
        container_name: user_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: user_db_password
            POSTGRES_DB: user_db
        ports:
            - "5432:5432"
        volumes:
            - user_data:/var/lib/postgresql/data

    product_db:
        image: postgres:15
        container_name: product_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: product_db_password
            POSTGRES_DB: product_db
        ports:
            - "5434:5432"
        volumes:
            - product_data:/var/lib/postgresql/data

volumes:
    user_data:
    product_data:
